### ISSUE TITLE
Auto-Apply profiles

### ISSUE THREAD

**Issue by Xkirnel99** [yoinx/kernel_adiutor#17]
I suggest this features because i was using it in "CPU control app" it enable the profile automatically without you apply it each moment like when "screen off" or "in-call", and with my experience i see it very professional. 

Best regards :D

**Comment by JoeSchubert** [comment]
I'm not entirely sure what you mean here. 

The app currently supports intents to switch profiles. You could use these from any app that does full phone state monitoring (like tasker, llama, or similar). It doesn't make much sense to add too many extra permissions to a kernel tweaking app just to monitor the phone for every possible state. 

This can also lead to a lot of extra CPU use (and battery use) due to the app having to always monitor the states.

Unless I misunderstand what you're asking for.

**Comment by RenderBroken** [comment]
The technical problem I see is like you say, monitoring screen off is not easy to do. For some phones screen off is different than say for the N6. So if you implemented such a feature you may end up with racing because of Ambient Display (Moto Display) and such. I also agree that tasker may be better to use here.

This way you are more inline with KA.
