### ISSUE TITLE
Sweep2wake missings controls

### ISSUE THREAD

**Issue by ajmtrz** [yoinx/kernel_adiutor#7]
Hello Yoinx. I have seen that missing controls in sweep2wake feature. Here I show you Flar2 xda post:

> Sweep2wake

Sweep2wake allows you to turn on your phone by swiping your finger across the screen. There are four sweep actions that will work

Gesture........Value
Sweep right......1
Sweep left........2
Sweep up.........4
Sweep down....8

Add up the values for each gesture you want to enable and put the total in /sys/android_touch/sweep2wake. For example, to enable all gestures, the value is 15 (1+2+4+8). To enable sweep right, sweep left and sweep up, the value is 7 (1+2+4)

/sys/android_touch/sweep2wake

**Comment by JoeSchubert** [comment]
I had broken this before because Grarak didn't allow for the correct choices. (see the removal commit here: https://github.com/yoinx/kernel_adiutor/commit/d6cb731a891958e4d37246df540bf185384486f8)

This will allow for all of the options correctly: https://github.com/yoinx/kernel_adiutor/commit/bbb9deea14b2f7414d5ae6298830cc52ca19e56a

If you're not building for yourself, it'll be in my next build (should be in the next few days)

**Comment by ajmtrz** [comment]
Ok, very thanks Yoinx. :)
